### ISSUE TITLE
404 when trying to use other language model

### ISSUE THREAD

**Issue by irony** [ljm625/syntaxnet-rest-api#1]
I'm trying to follow the instructions and have both tried to mount volume and add the files to the container in a separate Dockerfile but I get the same error (404). I suspect the error comes from nginx so maybe there is something else needed to allow queries to the language subpath?

```
curl -X POST -d '{ "strings": ["De äter pizza med ansjovis!","Knut satt på en knut och knöt en knut"] }' -H "Content-Type: application/json" http://localhost:9000/api/v1/query/Swedish

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>
```

**Comment by ljm625** [comment]
Hi irony,
Thanks for the issue feedback, I am sorry that I forget to push the latest docker image into the docker hub so that's why it show's 404, but you can build one using the docker file in the repo.
And when trying with swedish, I found out that there's some encoding issues. Trying to fix now 😄

**Comment by ljm625** [comment]
should be fixed, pls try again ;)
